/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Restaurant {
    int numberOfStars;
    String name;
    int priceCategory;

    Restaurant(int numberOfStars, String name, int priceCategory) {
        this.numberOfStars = numberOfStars;
        this.name = name;
        this.priceCategory = priceCategory;
    }

    public String toString() {
        return numberOfStars + " " + name + " " + priceCategory;
    }
}

