/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Arrays;

public class Library {
//    public boolean someLibraryMethod() {
//        return true;
//    }

//feature 1:
//Write a method called roll that accepts an integer n and rolls a d6 n times. This method should return an array containing the values of the rolls.
//example: roll(4) returns [3, 2, 1, 5]

//    public class dieRoll {
        public static int n = 4;
            public static void main(String[] args) {
            int[] die  = new int[6];
            for (int i = 0, i < 6; i++) die[i] = 0;

            for (int k = 0; k < n; k++) {
                int roll = (int) (6* Math.random() + 1);
                die[roll]++;
            }
            System.out.println("roll" + n);
        }
        for (int i = 1; i < 7; i++)
            System.out.println(Arrays.toString(die));
    }


//    public static void main(String[] args) {
//        int die = 6;
//        int randomRoll = (int) (Math.random() * die) + 1;
//        System.out.println(randomRoll);
//    }


//    public static int[] roll(int num) {
//        int max = 6;
//        int min = 1;
//        int range = max - min + 1;
//
//        for (int i = 0; i < 6; i++) {
//            int roll = (int)(Math.random() * range) + min;
//
//            System.out.println(random);
//        }
//    }
}


